name: cubix_mlops_pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.1.0
  - expat=2.6.3
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.9.20
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - alembic==1.13.3
      - aniso8601==9.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - databricks-sdk==0.36.0
      - deprecated==1.2.14
      - docker==7.1.0
      - flask==2.3.2
      - flask-babel==3.1.0
      - flask-cors==4.0.0
      - flask-restx
      - fonttools==4.54.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.35.0
      - graphene==3.4
      - graphql-core==3.2.5
      - graphql-relay==3.2.0
      - gunicorn==21.2.0
      - idna==3.10
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - mako==1.3.6
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mlflow==2.17.0
      - mlflow-skinny==2.17.0
      - numpy==1.25.2
      - opentelemetry-api==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - pandas==2.1.0
      - pillow==11.0.0
      - protobuf==5.28.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.20.0
      - rsa==4.9
      - scikit-learn==1.3.0
      - scipy==1.13.1
      - smmap==5.0.1
      - sqlalchemy==2.0.36
      - sqlparse==0.5.1
      - threadpoolctl==3.5.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - xgboost==2.0.3
      - zipp==3.20.2
